# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  S3_BUCKET_NAME: lufthouseimages
  AWS_ACCESS_KEY_ID: AKIAJ3QRBEBSO27YWXQQ
  AWS_SECRET_ACCESS_KEY: Y9tDzNFz9n3PvgP2+WjbkhxQAH6+AIehqvSIcvGp
  SC_SECRET_KEY: 6f93da5d9c48174ba23176b552bcd55b
  secret_key_base: 1c2d935ed064b7c8390e86b66982b98810b5c95bc7207a21d19bdb1c5fb60fe28d4e8ca21c0436dff17cdf5967ea7ce04e410c32880ceaa51ba68d8c08663346

test:
  secret_key_base: e1ca422f2c51ad196431dcccd1ebb590749896398bea328f32ddd1c9af73f83e2c5718937a98788516516b6bf2c7e715091d8822b8f77391881f2884a154dee4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  AWS_ACCESS_KEY_ID: AKIAJ3QRBEBSO27YWXQQ
  AWS_SECRET_ACCESS_KEY: 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
  SC_SECRET_KEY: 6f93da5d9c48174ba23176b552bcd55b
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
