# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  AWS_ACCESS_KEY_ID: ENV['AWS_ACCESS_KEY_ID']
  AWS_SECRET_ACCESS_KEY: ENV['AWS_SECRET_ACCESS_KEY']
  SC_SECRET_KEY: 6f93da5d9c48174ba23176b552bcd55b
  secret_key_base: ENV['SECRET_KEY_BASE']
  S3_BUCKET_NAME: ENV['S3_BUCKET_NAME']

test:
  secret_key_base: ENV['SECRET_KEY_BASE']

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  AWS_ACCESS_KEY_ID: AKIAIMYTRF5O6PP5R6MA
  AWS_SECRET_ACCESS_KEY: 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
  SC_SECRET_KEY: 6f93da5d9c48174ba23176b552bcd55b
  S3_BUCKET_NAME: 'lufthouseawsbucket'
  secret_key_base: e1ca422f2c51ad196431dcccd1ebb590749896398bea328f32ddd1c9af73f83e2c5718937a98788516516b6bf2c7e715091d8822b8f77391881f2884a154dee4
